---

- name: Remove old keys for regeneration
  connection: local
  file: path={{ item }} state=absent
  run_once: true
  with_items:
    - "{{new_keypath}}"
    - "{{new_keypath_pub}}"
    - "{{new_keypath_pem}}"
    - "{{new_keypath_ppk}}"

