---

- name: Create "{{ new_keypath_pub }}"
  connection: local
  shell: ssh-keygen -b {{ keygen.bits }} -t {{ keygen.encryption }} -f {{ new_keypath }} -q -N '' -C '{{ comment }}'
  run_once: true
  args:
    creates: "{{ new_keypath_pub }}"

- name: Create "{{ new_keypath_pem }}"
  connection: local
  shell: cp {{ new_keypath }} {{ new_keypath_pem }}
  run_once: true
  register: result_pem
  args:
    creates: "{{ new_keypath_pem }}"

- name: Is putty installed?
  connection: local
  shell: which puttygen
  run_once: true
  register: result_putty
  ignore_errors: yes

- name: Install putty
  connection: local
  shell: brew install putty
  run_once: true
  when: result_putty.failed is defined and result_putty.failed == true

- name: Create "{{ new_keypath_ppk }}"
  connection: local
  shell: puttygen {{ new_keypath }} -o {{ new_keypath_ppk }}
  run_once: true
  args:
    creates: "{{ new_keypath_ppk }}"
